name: C Compilation

on: push

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1.1

    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Set up MSVC environment
      shell: cmd
      run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl generate.c
          generate.exe

  
    - name: Upload Artifa
      uses: actions/upload-artifact@v3
      with:
          path: D:\a\stl60\stl60\msvc
          name: exe-windows.zip
